### ISSUE TITLE
CSS broken after removing "Password Form"

### ISSUE THREAD

**Issue by padey** [lukin/keywind#10]
Hey Anthony, 

I am currently playing with a Passwordless WebAuthn login. If I only display the user name in the Authentication Flow in the first step, the layout is destroyed and it no longer seems to load the CSS correctly. 

I have already gone through the logs and can't find an error anywhere... I assume that the password form is stored somewhere in login.ftl as binding? (Edit: Ok, I think that other FTL files such as "webauthn-authenticate.ftl" still need to be styled?)

See screenshot here:
<img width="426" alt="keywind-2step" src="https://user-images.githubusercontent.com/48521852/162946916-015590e2-c18c-46e1-93db-128602f01d18.png">

With the integrated theme it looks like this:
<img width="381" alt="keycloak" src="https://user-images.githubusercontent.com/48521852/162946913-e41464dc-4267-426a-b6d2-61bd8346d937.png">

My Authentication Flow looks like this:
<img width="775" alt="passwordless" src="https://user-images.githubusercontent.com/48521852/162949138-be77b92f-dc7e-4bf8-a3ba-cf15d3c645e7.png">

Best regards and thanks for your great work here! 

Patrick

**Comment by lukin** [comment]
Hi @padey

Yes, you are right. WebAuthn pages are not styled yet. I'm closing this issue then.
