### ISSUE TITLE
Show-hide Password button

### ISSUE THREAD

**Issue by tiphaineruy** [lukin/keywind#13]
Just a slight suggestion:

Add  a show/hide password option to the password input.

I might take that at some point but i'm not really familiar with the templating lib.

**Comment by shubham-vunet** [comment]
+1

**Comment by CHE1RON** [comment]
I guess that would be more of an `Alpine` thing rather than FreeMarker (the templating lib) - let me see if I come up with something for a project I'm currently using `keywind` for 😉

**Comment by paulwer** [comment]
hey folks, we did this in one of our projects today and have put a PR in for this repo to also use it.
great lib, we love to use it.❤️
@lukin
