### ISSUE TITLE
Unable to use non-email based usernames

### ISSUE THREAD

**Issue by andrejohansson** [lukin/keywind#2]
Thank you for your effort with this theme!

I found a small issue, and that is that email validation triggers even for usernames that are not emails.

1. Set `Email as username` to false for some realm

    ![image](https://user-images.githubusercontent.com/2828428/145239769-fd736899-443b-4592-a24d-3292403c977e.png)

1. Create a user with a non-email username, eg: `myuser`

1. Try to login, which will not be possible due to the validation firing

    ![image](https://user-images.githubusercontent.com/2828428/145240047-907da4ae-9d9c-4d78-b3b5-154d7e1568b9.png)

**Note**: This can cause you to be locked out from keycloak if you choose keywind as a theme for master realm and have an admin user without an email-like username.

Cheers!

**Comment by lukin** [comment]
@andrejohansson Hey 👋

Thank you for letting me know.

This should be fixed with 5a07825.
