### ISSUE TITLE
change title "KeyCloack" on the top of page

### ISSUE THREAD

**Issue by manimovassagh** [lukin/keywind#30]
hi,
Thanks for wonderful Theme.
I want to change the keycloack title on top of my page, But I can't find where to change this.
Can you please give me some info on that?

**Comment by hbadri3** [comment]
It is taking if from Display Name of your realm

**Comment by manimovassagh** [comment]
Thanks a lot :)

**Comment by lukin** [comment]
@hbadri3, thank you for your help with this issue.

**Comment by hbadri3** [comment]
@lukin my pleasure.
BTW I don't know if you could integrate the admin ui also because each time I have to build it from the official repo of keycloak and it is built with React
