### ISSUE TITLE
Login OTP pages.

### ISSUE THREAD

**Issue by hussamelvani** [lukin/keywind#4]
Thank you so much for the amazing work!

Do you have any plans to add OTP login pages (configuration, one time code, etc.) in the near future?

**Comment by lukin** [comment]
@hussamelvani Hey 👋

Thanks for bringing this issue up. I'm planning to do it.

**Comment by ronmrcdo** [comment]
Hi @lukin 

I created a PR for this. I hope you could check it. :)

https://github.com/lukin/keywind/pull/9

**Comment by lukin** [comment]
Hi @ronmrcdo

Thanks so much for the contribution.
