### ISSUE TITLE
Shared component freemarker library for multiple screens

### ISSUE THREAD

**Issue by charanraj-golla** [lukin/keywind#7]
Hi Anthony,
Thanks for sharing this project. I was trying to add a template for the account page and thought of sharing the components across login and account. Keycloak throws "Template not found for name ..." exception if I move the components directory under the keywind directory and make reference changes in the import URLs.  I was wondering if it is possible to achieve this.  

PS: I don't have much experience in Java and have not used Freemarker.

**Comment by lukin** [comment]
@charanraj-golla Hey 👋

I apologize for late reply. Possible solution to the issue:
https://lists.jboss.org/pipermail/keycloak-user/2015-May/002272.html
