### ISSUE TITLE
WebAuthn login not working on Firefox

### ISSUE THREAD

**Issue by dorianim** [lukin/keywind#73]
Hey there,

when trying to login using a yubikey on Firefox, I get the following error:
```
Uncaught ReferenceError: webAuthnAuthenticate is not defined
```
![image](https://github.com/lukin/keywind/assets/30153207/36c4e195-9f8b-4306-844f-9fe37c3e2c96)

It works in Chrome, though.

**Comment by scheibling** [comment]
@dorianim Looks like there's a previous error there above the webAuthnAuthenticate yellow part, is there a javascript error there as well? That might cause the webAuthAuthenticate function to not load correctly

**Comment by dorianim** [comment]
Just tried again and it seems to work now.
